language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ntambellini/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ntambellini/docker-react npm run test